- name: Install dependencies
  hosts: myhosts
  become: true
  vars_files:
    - vars/secrets.yml
  vars:
    db_name: strapi_tx
    db_user: strapi_tx_u
    domain_name: txcms.dicefriendly.com
    strapi_port: 1337
    strapi_user: strapi
    strapi_group: strapi
    app_dir: /opt/strapi
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - git
          - curl
          - build-essential
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python3-psycopg2
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download NodeSource GPG key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /etc/apt/keyrings/nodesource.asc
        mode: '0644'

    - name: Add NodeSource repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_20.x nodistro main"
        state: present

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true

    - name: Install PM2 globally
      community.general.npm:
        name: pm2
        global: true
        state: present

    - name: Create strapi group
      ansible.builtin.group:
        name: "{{ strapi_group }}"
        state: present

    - name: Create strapi user
      ansible.builtin.user:
        name: "{{ strapi_user }}"
        group: "{{ strapi_group }}"
        shell: /bin/bash
        home: "/home/{{ strapi_user }}"
        create_home: true
        system: false
        state: present

    - name: Create SSH directory for strapi user
      ansible.builtin.file:
        path: "/home/{{ strapi_user }}/.ssh"
        state: directory
        owner: "{{ strapi_user }}"
        group: "{{ strapi_group }}"
        mode: '0700'

    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ strapi_user }}"
        group: "{{ strapi_group }}"
        mode: '0755'

    - name: Generate PM2 startup script
      ansible.builtin.command:
        cmd: pm2 startup systemd -u {{ strapi_user }} --hp /home/{{ strapi_user }}
      register: pm2_startup
      changed_when: false

    - name: Execute PM2 startup command
      ansible.builtin.shell: "{{ pm2_startup.stdout_lines[-1] }}"
      when: pm2_startup.stdout_lines | length > 0
      args:
        creates: /etc/systemd/system/pm2-{{ strapi_user }}.service

    - name: Ensure PostgreSQL is running
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Create Strapi database
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present
      become_user: postgres

    - name: Create Strapi database user
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present
      become_user: postgres

    - name: Grant database privileges to Strapi user
      community.postgresql.postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        privs: ALL
        state: present
      become_user: postgres

    - name: Grant schema privileges to Strapi user
      community.postgresql.postgresql_privs:
        type: schema
        database: "{{ db_name }}"
        objs: public
        roles: "{{ db_user }}"
        privs: ALL
        state: present
      become_user: postgres

    - name: Create nginx site configuration
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/{{ domain_name }}
        content: |
          server {
              listen 80;
              server_name {{ domain_name }};

              client_max_body_size 100M;

              location / {
                  proxy_pass http://127.0.0.1:{{ strapi_port }};
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_cache_bypass $http_upgrade;
              }
          }
        mode: '0644'
        force: false
      notify: Reload nginx

    - name: Enable nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ domain_name }}
        dest: /etc/nginx/sites-enabled/{{ domain_name }}
        state: link
      notify: Reload nginx

    - name: Remove default nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload nginx

    - name: Ensure nginx is running
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

    - name: Flush handlers before certbot
      ansible.builtin.meta: flush_handlers

    - name: Obtain SSL certificate with certbot
      ansible.builtin.command:
        cmd: >
          certbot --nginx
          -d {{ domain_name }}
          --non-interactive
          --agree-tos
          --email {{ certbot_email }}
          --redirect
        creates: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
    - name: Create swap file
      ansible.builtin.command:
        cmd: fallocate -l 2G /swapfile
        creates: /swapfile

    - name: Set swap file permissions
      ansible.builtin.file:
        path: /swapfile
        mode: '0600'

    - name: Format swap file
      ansible.builtin.command:
        cmd: mkswap /swapfile
      when: ansible_swaptotal_mb == 0

    - name: Enable swap file
      ansible.builtin.command:
        cmd: swapon /swapfile
      when: ansible_swaptotal_mb == 0

    - name: Add swap to fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: '/swapfile none swap sw 0 0'
        state: present

  handlers:
    - name: Reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
